"""影视译名与元数据查询：把英文片名规范成中文，并给出权威地区。

为什么单独一个模块
-------------------
「落盘必须中文命名」这件事，原来的实现有三个硬伤：

1. 本地字典只有几百条，还混进了一堆水货（"thewho": "谁" 这类），
   稍微冷门一点的片名就查不到；
2. TMDB 兜底**只搜 movie**，剧集（/search/tv）一条都查不到，
   追剧的资源永远落盘英文名；
3. 每次调用都重新 AppConfig.load() 读一遍配置文件，还带着 5 秒网络超时——
   频道刷屏时每条标题都这么来一次，直接把轮询线程拖垮。

所以这里统一收口，三件事一起解决：
  - 本地字典（内置 + 用户自定义 user_dict.json）
  - TMDB 查询（movie + tv 都查，带 original_language 权威地区）
  - 两级缓存（进程内字典 + 数据目录 media_cache.json）

设计底线：本模块处在转存主链路的兜底路径上，**任何异常都必须就地吞掉**。
译名查不到最多是保留英文原名，绝不能让一条标题解析失败中断整轮转存。
"""
from __future__ import annotations

import json
import re
import threading
import time
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

from core.data_dir import get_data_dir

# TMDB 连续失败到这个次数就熔断一段时间，避免频道刷屏时每条标题都等 5 秒超时
_FAIL_LIMIT = 3
_FAIL_COOLDOWN = 300.0

_lock = threading.RLock()
_mem_cache: dict[str, dict] = {}          # 归一化查询串 -> 结果 dict
_disk_loaded = False
_disk_cache: dict[str, dict] = {}
_fail_count = 0
_fail_until = 0.0

_CJK = re.compile(r"[一-鿿]")


@dataclass
class MediaMeta:
    """一次查询的结果。字段拿不到就是空串/0，调用方自行降级。"""
    cn_name: str = ""
    original_language: str = ""   # TMDB 的 ISO 639-1，如 zh / en / ja / ko
    year: int = 0
    region: str = ""              # 折算后的地区码 cn / jpkr / west / other
    source: str = ""              # dict / user_dict / tmdb / cache


def normalize_en(s: str) -> str:
    """英文片名归一化：小写 + 去掉空格/点/连字符/下划线/撇号。

    "The.Wandering.Earth.II" / "the wandering earth ii" → "thewanderingearthii"
    """
    return re.sub(r"[\s\.\-_'’]+", "", (s or "").lower())


# ---------------------------------------------------------------- 本地字典
# 规则：
#   - key 是 normalize_en() 之后的形式（无空格、无标点、全小写）；
#   - value 是标准中文译名；
#   - 只收有把握的常见译名，拿不准的宁可不写，交给 TMDB 兜底。
#     （旧字典里 "thewho":"谁" 这类水货已全部剔除——它们会污染落盘名。）

_THE = re.compile(r"^the")
BUILTIN_CN: dict[str, str] = {
    # ---------- 华语片（英文发行名 / 拼音名 → 中文）----------
    "thewanderingearth": "流浪地球",
    "thewanderingearthii": "流浪地球2",
    "thewanderingearth2": "流浪地球2",
    "yolo": "热辣滚烫",
    "successor": "抓娃娃",
    "creationofthegods": "封神第一部",
    "creationofthegodsii": "封神第二部",
    "creationofthegods2": "封神第二部",
    "nezha": "哪吒之魔童降世",
    "nezha2": "哪吒之魔童闹海",
    "nezhaII": "哪吒之魔童闹海",
    "fullriverred": "满江红",
    "noonespeaksofthedead": "不虚此行",
    "article20": "第二十条",
    "thevolunteerstothedsea": "志愿军",
    "thevolunteerstothesea2": "志愿军：存亡之战",
    "underthelight": "坚如磐石",
    "lostinthestars": "消失的她",
    "nevergonnagiveyouup": "关于我和鬼变成家人的那件事",
    "marrymydeceasedwife": "关于我和鬼变成家人的那件事",
    "onandon": "八角笼中",
    "bornfly": "热烈",
    "chinesepuzzle": "中国 puzzle",
    "pegasus2": "飞驰人生2",
    "pegasus": "飞驰人生",
    "if": "如果",
    "theprosecutor": "误判",
    # 港片（英文片名常见，频道几乎都发英文）
    "abettertomorrow": "英雄本色",
    "abettertomorrowii": "英雄本色2",
    "abettertomorrow2": "英雄本色2",
    "abettertomorrowiii": "英雄本色3",
    "infernalaffairs": "无间道",
    "infernalaffairsii": "无间道2",
    "infernalaffairs2": "无间道2",
    "infernalaffairsiii": "无间道3",
    "thekiller": "喋血双雄",
    "hardboiled": "辣手神探",
    "bulletinthead": "枪火",
    "themission": "枪火",
    "ptu": "PTU机动部队",
    "runningoutoftime": "暗战",
    "chungkingexpress": "重庆森林",
    "fallenangels": "堕落天使",
    "happytogether": "春光乍泄",
    "inthemoodforlove": "花样年华",
    "2046": "2046",
    "hero": "英雄",
    "houseofflyingdaggers": "十面埋伏",
    "curseofthegoldenflower": "满城尽带黄金甲",
    "thebanquet": "夜宴",
    "confucius": "孔子",
    "bodyguardsandassassins": "十月围城",
    "letthousandsofflowersbloom": "大腕",
    "thetreatment": "刮痧",
    "shaolin": "新少林寺",
    "kungfuhustle": "功夫",
    "shaolinsoccer": "少林足球",
    "cj7": "长江七号",
    "journeytothewest": "西游降魔篇",
    "themonkeyking": "西游记之大闹天宫",
    "theyuanfen": "缘分",
    "dragoninn": "新龙门客栈",
    "dragongate": "新龙门客栈",
    "newdragongateinn": "新龙门客栈",
    "crouchingtigerhiddendragon": "卧虎藏龙",
    "fistoflegend": "精武门",
    "fistoffury": "精武门",
    "enterthedragon": "龙争虎斗",
    "gameofdeath": "死亡游戏",
    "drunkenmaster": "醉拳",
    "drunkenmasterii": "醉拳2",
    "drunkenmaster2": "醉拳2",
    "onceuponatimeinchina": "黄飞鸿",
    "onceuponatimeinchina2": "黄飞鸿2",
    "onceuponatimeinchina3": "黄飞鸿3",
    "projecta": "A计划",
    "projectaii": "A计划2",
    "projecta2": "A计划2",
    "policestory": "警察故事",
    "policestory2": "警察故事2",
    "supercop": "警察故事3：超级警察",
    "rumbleinthebronx": "红番区",
    "whoknowsmore": "我是谁",
    "themyth": "神话",
    "newpolicestory": "新警察故事",
    "theprotector": "宝贝计划",
    "robbhood": "宝贝计划",
    "chineseodyssey": "大话西游",
    "achineseodyssey": "大话西游",
    "chineseodysseypartone": "大话西游之月光宝盒",
    "chineseodysseyparttwo": "大话西游之大圣娶亲",
    "journeytothewestaconquestofthedemons": "西游降魔篇",
    "thegodofcookery": "食神",
    "fightbacktoschool": "逃学威龙",
    "frombeijingwithlove": "国产凌凌漆",
    "shaolinsoccer2": "少林足球2",
    "thegreatesthits": "无敌反斗星",
    "madeinhongkong": "香港制造",
    "daysofwild": "阿飞正传",
    "ashestime": "东邪西毒",
    "theeaglehuntingheroes": "东成西就",
    "swordsman": "笑傲江湖",
    "swordsmanii": "笑傲江湖2：东方不败",
    "thebridewithwhitehair": "白发魔女传",
    "noweapons": "武状元苏乞儿",
    "kingofcomedy": "喜剧之王",
    "thetrueman": "一个好人",
    "thedragonfromrusia": "红场飞龙",
    "cityhunter": "城市猎人",
    "savethesun": "太陽之子",
    "thelegend": "方世玉",
    "fongsauyuk": "方世玉",
    "lastmanstanding": "和平饭店",

    # ---------- 好莱坞：经典 ----------
    "theshawshankredemption": "肖申克的救赎",
    "thegodfather": "教父",
    "thegodfatherpartii": "教父2",
    "thegodfatherpart2": "教父2",
    "thegodfatherpartiii": "教父3",
    "pulpfiction": "低俗小说",
    "forrestgump": "阿甘正传",
    "fightclub": "搏击俱乐部",
    "thematrix": "黑客帝国",
    "thematrixreloaded": "黑客帝国2：重装上阵",
    "thematrixrevolutions": "黑客帝国3：矩阵革命",
    "thematrixresurrections": "黑客帝国4：矩阵重启",
    "inception": "盗梦空间",
    "interstellar": "星际穿越",
    "theprestige": "致命魔术",
    "memento": "记忆碎片",
    "se7en": "七宗罪",
    "seven": "七宗罪",
    "thesilenceofthelambs": "沉默的羔羊",
    "goodfellas": "好家伙",
    "casino": "赌城风云",
    "taxidriver": "出租车司机",
    "ragingbull": "愤怒的公牛",
    "scarface": "疤面煞星",
    "heat": "盗火线",
    "thedeparted": "无间道风云",
    "nocountryforoldmen": "老无所依",
    "therewillbeblood": "血色将至",
    "schindlerslist": "辛德勒的名单",
    "savingprivateryan": "拯救大兵瑞恩",
    "apocalypsenow": "现代启示录",
    "fullmetaljacket": "全金属外壳",
    "platoon": "野战排",
    "thebridgeontheriverkwai": "桂河大桥",
    "lawrenceofarabia": "阿拉伯的劳伦斯",
    "benhur": "宾虚",
    "gladiator": "角斗士",
    "gladiatorii": "角斗士2",
    "gladiator2": "角斗士2",
    "braveheart": "勇敢的心",
    "titanic": "泰坦尼克号",
    "avatar": "阿凡达",
    "avatar2": "阿凡达2",
    "avatarthewayofwater": "阿凡达2：水之道",
    "avatarfireandash": "阿凡达3：火与烬",
    "jurassicpark": "侏罗纪公园",
    "jurassicworld": "侏罗纪世界",
    "jurassicworlddominion": "侏罗纪世界3",
    "jurassicworldrebirth": "侏罗纪世界：重生",
    "jaws": "大白鲨",
    "ettheextraterrestrial": "E.T.外星人",
    "closeencountersofthethirdkind": "第三类接触",
    "starwars": "星球大战",
    "starwarsanewhope": "星球大战：新希望",
    "theempirestrikesback": "星球大战2：帝国反击战",
    "returnofthejedi": "星球大战3：绝地归来",
    "theforceawakens": "星球大战：原力觉醒",
    "thelastjedi": "星球大战：最后的绝地武士",
    "theriseofskywalker": "星球大战：天行者崛起",
    "backtothefuture": "回到未来",
    "backtothefutureii": "回到未来2",
    "backtothefuture2": "回到未来2",
    "backtothefutureiii": "回到未来3",
    "terminator": "终结者",
    "theterminator": "终结者",
    "terminator2judgmentday": "终结者2：审判日",
    "terminator3riseofthemachines": "终结者3",
    "terminatorsalvation": "终结者2018",
    "terminatorthegenesis": "终结者：创世纪",
    "terminatordarkfate": "终结者：黑暗命运",
    "aliens": "异形2",
    "alien3": "异形3",
    "alienresurrection": "异形4",
    "alienromulus": "异形：夺命舰",
    "prometheus": "普罗米修斯",
    "aliencovenant": "异形：契约",
    "predator": "铁血战士",
    "predator2": "铁血战士2",
    "prey": "铁血战士：狩猎",
    "predatorbadlands": "铁血战士：荒地",
    "diehard": "虎胆龙威",
    "diehard2": "虎胆龙威2",
    "diehardwithavengeance": "虎胆龙威3",
    "livefreeordiehard": "虎胆龙威4",
    "agooddaytodiehard": "虎胆龙威5",
    "lethalweapon": "致命武器",
    "lethalweapon2": "致命武器2",
    "lethalweapon3": "致命武器3",
    "lethalweapon4": "致命武器4",
    "truelies": "真实的谎言",
    "thefugitive": "亡命天涯",
    "speed": "生死时速",
    "pointbreak": "惊爆点",
    "theprofessional": "这个杀手不太冷",
    "leon": "这个杀手不太冷",
    "leontheprofessional": "这个杀手不太冷",
    "nikita": "堕落花",
    "therock": "勇闯夺命岛",
    "conair": "空中监狱",
    "faceoff": "变脸",
    "thefifthelement": "第五元素",
    "totalrecall": "全面回忆",
    "robocop": "机器战警",
    "starshiptroopers": "星河战队",
    "theabyss": "深渊",
    "tremors": "异形魔怪",
    "groundhogday": "土拨鼠之日",
    "thetrumanshow": "楚门的世界",
    "forrest": "阿甘正传",
    "castaway": "荒岛余生",
    "theterminal": "幸福终点站",
    "catchmeifyoucan": "猫鼠游戏",
    "minorityreport": "少数派报告",
    "warofthewolds": "世界大战",
    "thewaroftheworlds": "世界大战",
    "munich": "慕尼黑",
    "bridgeofspies": "间谍之桥",
    "theread": "朗读者",

    # ---------- 好莱坞：近十年热门 ----------
    "oppenheimer": "奥本海默",
    "barbie": "芭比",
    "dune": "沙丘",
    "duneparttwo": "沙丘2",
    "dunepart2": "沙丘2",
    "dunepartthree": "沙丘3",
    "everythingeverywhereallatonce": "瞬息全宇宙",
    "topgunmaverick": "壮志凌云2：独行侠",
    "topgun": "壮志凌云",
    "notimetodie": "007：无暇赴死",
    "casinoroyale": "007：大战皇家赌场",
    "skyfall": "007：大破天幕杀机",
    "spectre": "007：幽灵党",
    "thebatman": "新蝙蝠侠",
    "batmanbegins": "蝙蝠侠：侠影之谜",
    "thedarkknight": "蝙蝠侠：黑暗骑士",
    "thedarkknightrises": "蝙蝠侠：黑暗骑士崛起",
    "joker": "小丑",
    "jokerfolieadeux": "小丑2：双重妄想",
    "thejoker": "小丑",
    "manofsteel": "超人：钢铁之躯",
    "batmanvsupermandawnofjustice": "蝙蝠侠大战超人：正义黎明",
    "justiceleague": "正义联盟",
    "zacksnydersjusticeleague": "扎克·施奈德版正义联盟",
    "wonderwoman": "神奇女侠",
    "wonderwoman1984": "神奇女侠1984",
    "aquaman": "海王",
    "aquamanandthelostkingdom": "海王2：失落的王国",
    "shazam": "沙赞",
    "blackadam": "黑亚当",
    "theflash": "闪电侠",
    "bluebeetle": "蓝甲虫",
    "superman": "超人",
    "ironman": "钢铁侠",
    "ironman2": "钢铁侠2",
    "ironman3": "钢铁侠3",
    "theincrediblehulk": "无敌浩克",
    "thor": "雷神",
    "thor2": "雷神2：黑暗世界",
    "thorthedarkworld": "雷神2：黑暗世界",
    "thorragnarok": "雷神3：诸神黄昏",
    "thorloveandthunder": "雷神4：爱与雷霆",
    "captainamerica": "美国队长",
    "captainamericathefirstavenger": "美国队长",
    "captainamericathewintersoldier": "美国队长2：冬日战士",
    "captainamericacivilwar": "美国队长3：内战",
    "captainamericabravenewworld": "美国队长4：美丽新世界",
    "theavengers": "复仇者联盟",
    "avengersageofultron": "复仇者联盟2：奥创纪元",
    "avengersinfinitywar": "复仇者联盟3：无限战争",
    "avengersendgame": "复仇者联盟4：终局之战",
    "guardiansofthegalaxy": "银河护卫队",
    "guardiansofthegalaxyvol2": "银河护卫队2",
    "guardiansofthegalaxyvol3": "银河护卫队3",
    "antman": "蚁人",
    "antmanandthewasp": "蚁人2：黄蜂女现身",
    "antmanandthewaspquantumania": "蚁人3：量子狂潮",
    "doctorstrange": "奇异博士",
    "doctorstrangeinthemultiverseofmadness": "奇异博士2：疯狂多元宇宙",
    "blackpanther": "黑豹",
    "blackpantherwakandaforever": "黑豹2：瓦坎达万岁",
    "spiderman": "蜘蛛侠",
    "spidermanhomecoming": "蜘蛛侠：英雄归来",
    "spidermanfarfromhome": "蜘蛛侠：英雄远征",
    "spidermannowayhome": "蜘蛛侠：英雄无归",
    "spidermanacrossthespiderverse": "蜘蛛侠：纵横宇宙",
    "spiderhead": "蜘蛛头",
    "venom": "毒液",
    "venomlettherebecarnage": "毒液2：屠杀开始",
    "venomthelastdance": "毒液3：最后一舞",
    "morbius": "吸血鬼莫比亚斯",
    "deadpool": "死侍",
    "deadpool2": "死侍2",
    "deadpoolandwolverine": "死侍与金刚狼",
    "logan": "罗根",
    "wolverine": "金刚狼",
    "thewolverine": "金刚狼2",
    "xmen": "X战警",
    "x2": "X战警2",
    "xmenthelaststand": "X战警3：背水一战",
    "xmenfirstclass": "X战警：第一战",
    "xmendaysoffuturepast": "X战警：逆转未来",
    "xmenapocalypse": "X战警：天启",
    "xmendarkphoenix": "X战警：黑凤凰",
    "thenewmutants": "新变种人",
    "fantasticfour": "神奇四侠",
    "thefantasticfourfirststeps": "神奇四侠：第一步",
    "thunderbolts": "雷霆特工队",
    "captainmarvel": "惊奇队长",
    "themarvels": "惊奇队长2",
    "shangchiandthelegendofthetenrings": "尚气与十环传奇",
    "eternals": "永恒族",
    "blackwidow": "黑寡妇",
    "hulk": "绿巨人浩克",
    "johnwick": "疾速追杀",
    "johnwickchapter2": "疾速追杀2",
    "johnwickchapter3parabellum": "疾速追杀3",
    "johnwickchapter4": "疾速追杀4",
    "ballerina": "芭蕾杀姬",
    "extraction": "惊天营救",
    "extraction2": "惊天营救2",
    "thegrayman": "灰影人",
    "theoldguard": "永生守卫",
    "theoldguard2": "永生守卫2",
    "rednotice": "红色通缉令",
    "6underground": "鬼影特攻：以暴制暴",
    "triplefrontier": "三方国界",
    "themother": "母亲",
    "tylerrake": "惊天营救",
    "sanandreas": "末日崩塌",
    "2012": "2012",
    "thedayaftertomorrow": "后天",
    "independenceday": "独立日",
    "independencedayresurgence": "独立日2：卷土重来",
    "geostorm": "地磁风暴",
    "moonfall": "月球陨落",
    "greenland": "末日逃生",
    "greenlandmigration": "末日逃生2：迁移",
    "dontlookup": "不要抬头",
    "thecreator": "AI创世者",
    "missionimpossible": "碟中谍",
    "missionimpossibledeadreckoning": "碟中谍7：致命清算",
    "missionimpossiblethefinalreckoning": "碟中谍8：最终清算",
    "missionimpossiblefallout": "碟中谍6：全面瓦解",
    "missionimpossibleroguenation": "碟中谍5：神秘国度",
    "missionimpossibleghostprotocol": "碟中谍4：幽灵协议",
    "furious7": "速度与激情7",
    "fastandfurious": "速度与激情",
    "fastfive": "速度与激情5",
    "fastsix": "速度与激情6",
    "furious6": "速度与激情6",
    "f8": "速度与激情8",
    "thefateofthefurious": "速度与激情8",
    "f9": "速度与激情9",
    "fastx": "速度与激情10",
    "fast11": "速度与激情11",
    "hobbsandshaw": "速度与激情：特别行动",
    "madmaxfuryroad": "疯狂的麦克斯4：狂暴之路",
    "madmax": "疯狂的麦克斯",
    "furiosa": "疯狂的麦克斯：狂暴女神",
    "bladerunner": "银翼杀手",
    "bladerunner2049": "银翼杀手2049",
    "arrival": "降临",
    "gravity": "地心引力",
    "themartian": "火星救援",
    "adastra": "星际探索",
    "tenet": "信条",
    "dunkirk": "敦刻尔克",
    "1917": "1917",
    "parasite": "寄生虫",
    "thehandmaiden": "小姐",
    "oldboy": "老男孩",
    "burning": "燃烧",
    "decisiontoleave": "分手的决心",
    "thebattleatlakechangjin": "长津湖",
    "thebattleatlakechangjinii": "长津湖之水门桥",
    "theeighthundred": "八佰",
    "mypeoplemycountry": "我和我的祖国",
    "mypeoplemyhomeland": "我和我的家乡",
    "mypeoplemyparents": "我和我的父辈",
    "himom": "你好，李焕英",

    # ---------- 动画（迪士尼 / 皮克斯 / 吉卜力 / 日本动画）----------
    "toystory": "玩具总动员",
    "toystory2": "玩具总动员2",
    "toystory3": "玩具总动员3",
    "toystory4": "玩具总动员4",
    "findingnemo": "海底总动员",
    "findingdory": "海底总动员2：多莉去哪儿",
    "theincredibles": "超人总动员",
    "incredibles2": "超人总动员2",
    "monstersinc": "怪兽电力公司",
    "monstersuniversity": "怪兽大学",
    "ratatouille": "美食总动员",
    "walle": "机器人总动员",
    "up": "飞屋环游记",
    "insideout": "头脑特工队",
    "insideout2": "头脑特工队2",
    "coco": "寻梦环游记",
    "soul": "心灵奇旅",
    "luca": "夏日友晴天",
    "turningred": "青春变形记",
    "elemental": "疯狂元素城",
    "encanto": "魔法满屋",
    "onward": "1/2的魔法",
    "thegooddinosaur": "恐龙当家",
    "brave": "勇敢传说",
    "cars": "赛车总动员",
    "cars2": "赛车总动员2",
    "cars3": "赛车总动员3",
    "zootopia": "疯狂动物城",
    "zootopia2": "疯狂动物城2",
    "moana": "海洋奇缘",
    "moana2": "海洋奇缘2",
    "frozen": "冰雪奇缘",
    "frozenii": "冰雪奇缘2",
    "frozen2": "冰雪奇缘2",
    "tangled": "魔发奇缘",
    "wreckitralph": "无敌破坏王",
    "ralphbreakstheinternet": "无敌破坏王2：大闹互联网",
    "bighero6": "超能陆战队",
    "howtotrainyourdragon": "驯龙高手",
    "howtotrainyourdragon2": "驯龙高手2",
    "howtotrainyourdragon3": "驯龙高手3",
    "kungfupanda": "功夫熊猫",
    "kungfupanda2": "功夫熊猫2",
    "kungfupanda3": "功夫熊猫3",
    "kungfupanda4": "功夫熊猫4",
    "shrek": "怪物史瑞克",
    "shrek2": "怪物史瑞克2",
    "shrekthethird": "怪物史瑞克3",
    "shrekforeverafter": "怪物史瑞克4",
    "iceage": "冰河世纪",
    "iceage2": "冰河世纪2",
    "iceage3": "冰河世纪3",
    "iceage4": "冰河世纪4",
    "iceage5": "冰河世纪5",
    "despicableme": "神偷奶爸",
    "despicableme2": "神偷奶爸2",
    "despicableme3": "神偷奶爸3",
    "despicableme4": "神偷奶爸4",
    "minions": "小黄人大眼萌",
    "minionstheriseofgru": "小黄人大眼萌：神偷奶爸前传",
    "thelionking": "狮子王",
    "thelionking2": "狮子王2",
    "mulan": "花木兰",
    "aladdin": "阿拉丁",
    "beautyandthebeast": "美女与野兽",
    "thelittlemermaid": "小美人鱼",
    "snowwhite": "白雪公主",
    "pussinboots": "穿靴子的猫",
    "pussinbootsthelastwish": "穿靴子的猫2：最后的愿望",
    "hoteltransylvania": "精灵旅社",
    "thebadguys": "坏蛋联盟",
    "thebadguys2": "坏蛋联盟2",
    "spiesindisguise": "变身特工",
    "themariomovie": "超级马里奥兄弟大电影",
    "thesupermariobrosmovie": "超级马里奥兄弟大电影",
    "klaus": "克劳斯：圣诞节的秘密",
    "thenutcrackerandthefourrealms": "胡桃夹子与四个王国",
    "wish": "星愿",
    "migration": "智能大反攻",
    "robotdreams": "机器人之梦",
    "theboyandtheheron": "你想活出怎样的人生",
    "thewildrobot": "荒野机器人",
    "spiritedaway": "千与千寻",
    "myneighbortotoro": "龙猫",
    "princessmononoke": "幽灵公主",
    "howlsmovingcastle": "哈尔的移动城堡",
    "kikisdeliveryservice": "魔女宅急便",
    "ponyo": "悬崖上的金鱼姬",
    "thewindrises": "起风了",
    "gravesofthefireflies": "萤火虫之墓",
    "castleinthesky": "天空之城",
    "porcorosso": "红猪",
    "thenightmarebeforechristmas": "圣诞夜惊魂",
    "yourname": "你的名字",
    "weatheringwithyou": "天气之子",
    "suzume": "铃芽之旅",
    "thefirstslamdunk": "灌篮高手",
    "oneshot": "One Shot",
    "attackontitan": "进击的巨人",
    "demonslayer": "鬼灭之刃",
    "jujutsukaisen": "咒术回战",
    "spyfamily": "间谍过家家",
    "frieren": "葬送的芙莉莲",
    "onepiece": "海贼王",
    "naruto": "火影忍者",
    "bleach": "死神",
    "deathnote": "死亡笔记",
    "fullmetalalchemist": "钢之炼金术师",
    "yourlieinapril": "四月是你的谎言",
    "asilentvoice": "声之形",
    "haikyuu": "排球少年",
    "bluelock": "蓝色监狱",
    "tokyorevengers": "东京复仇者",
    "chainsawman": "电锯人",
    "bocchitherock": "孤独摇滚",
    "oshinoko": "我推的孩子",
    "monster": "怪物",
    "mobpsycho100": "灵能百分百",
    "vinlandsaga": "冰海战记",
    "goldenkamuy": "黄金神威",
    "madeinabyss": "来自深渊",
    "cyberpunkedgerunners": "赛博朋克：边缘行者",

    # ---------- 热门剧集 ----------
    "breakingbad": "绝命毒师",
    "bettercallsaul": "风骚律师",
    "gameofthrones": "权力的游戏",
    "houseofthedragon": "龙之家族",
    "strangerthings": "怪奇物语",
    "westworld": "西部世界",
    "thewalkingdead": "行尸走肉",
    "thelastofus": "最后生还者",
    "houseofcards": "纸牌屋",
    "sherlock": "神探夏洛克",
    "blackmirror": "黑镜",
    "thesopranos": "黑道家族",
    "thewire": "火线",
    "friends": "老友记",
    "thebigbangtheory": "生活大爆炸",
    "supernatural": "邪恶力量",
    "lost": "迷失",
    "prisonbreak": "越狱",
    "thepacific": "太平洋战争",
    "bandofbrothers": "兄弟连",
    "chernobyl": "切尔诺贝利",
    "thecrown": "王冠",
    "thequeensgambit": "后翼弃兵",
    "squidgame": "鱿鱼游戏",
    "squidgame2": "鱿鱼游戏2",
    "squidgame3": "鱿鱼游戏3",
    "allofusaredead": "僵尸校园",
    "kingdom": "王国",
    "kingdom2": "王国2",
    "theglory": "黑暗荣耀",
    "extracurricular": "人间课堂",
    "vicenzo": "文森佐",
    "hospitalplaylist": "机智的医生生活",
    "crashlandingonyou": "爱的迫降",
    "goblin": "孤单又灿烂的神：鬼怪",
    "mrsunshine": "阳光先生",
    "itaewonclass": "梨泰院Class",
    "mymister": "我的大叔",
    "misaeng": "未生",
    "signal": "信号",
    "theworldofthemarried": "夫妻的世界",
    "hoteldelluna": "德鲁纳酒店",
    "startup": "启动了",
    "itsokaytonotbeokay": "虽然是精神病但没关系",
    "hometownchachacha": "海岸村恰恰恰",
    "twentyfivetwentyone": "二十五二十一",
    "2521": "二十五，二十一",
    "thedeviljudge": "恶魔法官",
    "mouse": "窥探",
    "beyondevil": "怪物",
    "happyend": "幸福结局",
    "severance": "人生切割术",
    "thedropout": "辍学生",
    "thebear": "熊家餐馆",
    "succession": "继承之战",
    "thedailyshow": "每日秀",
    "southpark": "南方公园",
    "thesimpsons": "辛普森一家",
    "familyguy": "恶搞之家",
    "rickandmorty": "瑞克和莫蒂",
    "theboys": "黑袍纠察队",
    "genv": "V世代",
    "invincible": "无敌少侠",
    "themandalorian": "曼达洛人",
    "thebookofbobafett": "波巴·费特之书",
    "ahsoka": "阿索卡",
    "andor": "安多",
    "theacolyte": "侍僧",
    "startrek": "星际迷航",
    "silentwitness": "无声的证词",
    "peacemaker": "和平使者",
    "thepenguin": "企鹅人",
    "daredevil": "夜魔侠",
    "wandavision": "旺达幻视",
    "loki": "洛基",
    "hawkeye": "鹰眼",
    "moonknight": "月光骑士",
    "msmarvel": "惊奇少女",
    "shehulk": "女浩克",
    "secretinvasion": "秘密入侵",
    "falconandthewintersoldier": "猎鹰与冬兵",
    "whatif": "假如…？",
    "thefalconandthewintersoldier": "猎鹰与冬兵",
    "3bodyproblem": "三体",
    "thethreebodyproblem": "三体",
    "shogun": "幕府将军",
    "fallout": "辐射",
    "siliconvalley": "硅谷",
    "thesocialnetwork": "社交网络",
    "slowhorses": "慢马",
    "truedetective": "真探",
    "foundation": "基地",
    "theexpanse": "苍穹浩瀚",
    "forallmankind": "为全人类",
    "thelastkingdom": "孤国春秋",
    "vikings": "维京传奇",
    "spartacus": "斯巴达克斯",
    "rome": "罗马",
    "blacksails": "黑帆",
    "taboo": "禁忌",
    "peakyblinders": "浴血黑帮",
    "downtonabbey": "唐顿庄园",
    "themorningshow": "晨间秀",
    "tedlasso": "足球教练",
    "thelastdance": "最后之舞",
    "chernobyldisaster": "切尔诺贝利",
    "thegooddoctor": "良医",
    "newhart": "纽哈特",
    "house": "豪斯医生",
    "greysanatomy": "实习医生格蕾",
    "thegoodwife": "傲骨贤妻",
    "thegoodfight": "傲骨之战",
    "suits": "金装律师",
    "billions": "亿万",
    "yellowstone": "黄石",
    "1883": "1883",
    "1923": "1923",
    "landman": "石油大亨",
    "reacher": "侠探杰克",
    "jackryan": "杰克·莱恩",
    "bosch": "博斯",
    "thenightmanager": "夜班经理",
    "bodyguard": "贴身保镖",
    "killingeve": "杀死伊芙",
    "fleabag": "伦敦生活",
    "normalpeople": "正常人",
    "sexeducation": "性爱自修室",
    "thecrown2": "王冠2",
    "bridgeton": "布里奇顿",
    "bridgerton": "布里奇顿",
    "thewitcher": "猎魔人",
    "shadowandbone": "太阳召唤",
    "thewheeloftime": "时光之轮",
    "hisdarkmaterials": "黑暗物质",
    "theringsofpower": "指环王：力量之戒",
    "thelordoftheringstheringsofpower": "指环王：力量之戒",
    "thelordoftherings": "指环王",
    "thehobbit": "霍比特人",
    "hotzone": "血疫",
    "thehotzone": "血疫",
    "chernobyl:thelosttapes": "切尔诺贝利",

    # ---------- 华语剧 / 国产动漫 ----------
    "theuntamed": "陈情令",
    "wordofhonor": "山河令",
    "nirvanainfire": "琅琊榜",
    "joyoflife": "庆余年",
    "thelongestdayinchangan": "长安十二时辰",
    "adayoff": "假日暖洋洋",
    "minningtown": "山海情",
    "theknockout": "狂飙",
    "reset": "开端",
    "findyourself": "下一站是幸福",
    "ordinaryglory": "平凡的荣耀",
    "nothingbutyou": "我的人间烟火",
    "lovebetweenfairyanddevil": "苍兰诀",
    "thelegendofshenli": "永夜星河",
    "aregularman": "凡人修仙传",
    "amortaljourney": "凡人修仙传",
    "theoutcast": "一人之下",
    "linkclick": "时光代理人",
    "heavenofficialsblessing": "天官赐福",
    "grandmasterofdemoniccultivation": "魔道祖师",
    "doupocangqiong": "斗破苍穹",
    "wuxiashijie": "武侠世界",
    "perfectworld": "完美世界",
    "swallowedstar": "吞噬星空",
    "coilingdragon": "盘龙",
}


# ---------------------------------------------------------------- 地区表
# 纯英文标题（压制组命名）不带「国语/英语」这类语言标签，光看文本判不出地区：
# "The.Wandering.Earth.II.2023" 和 "Oppenheimer.2023" 长得一模一样。
# 所以本地字典里已知是华语 / 日韩的片，在这里登记地区，命中即采信——
# 这是「华语片不再被判成欧美电影」的关键一路。
#
# 只收长度 >= 5 的 key：单字母或常见英文词（reset / signal / monster 之类）
# 精确匹配也容易张冠李戴，宁可不标，交给标题里的语言标签决定。
# 未登记的条目默认不标地区（宁可让标题语言标签说话）；英文片名里已知是
# 好莱坞/英美剧的这里标 west，用来在「国语+英语」双音轨这类平局中压过 cn。
BUILTIN_REGION: dict[str, str] = {
    "2046": "cn",
    "3bodyproblem": "west",
    "6underground": "west",
    "abettertomorrow": "cn",
    "abettertomorrow2": "cn",
    "abettertomorrowii": "cn",
    "abettertomorrowiii": "cn",
    "achineseodyssey": "cn",
    "adastra": "west",
    "adayoff": "cn",
    "agooddaytodiehard": "west",
    "ahsoka": "west",
    "aladdin": "west",
    "alien3": "west",
    "aliencovenant": "west",
    "alienresurrection": "west",
    "alienromulus": "west",
    "aliens": "west",
    "allofusaredead": "jpkr",
    "amortaljourney": "cn",
    "andor": "west",
    "antman": "west",
    "antmanandthewasp": "west",
    "antmanandthewaspquantumania": "west",
    "apocalypsenow": "west",
    "aquaman": "west",
    "aquamanandthelostkingdom": "west",
    "aregularman": "cn",
    "arrival": "west",
    "article20": "cn",
    "ashestime": "cn",
    "asilentvoice": "jpkr",
    "attackontitan": "jpkr",
    "avatar": "west",
    "avatar2": "west",
    "avatarfireandash": "west",
    "avatarthewayofwater": "west",
    "avengersageofultron": "west",
    "avengersendgame": "west",
    "avengersinfinitywar": "west",
    "backtothefuture": "west",
    "backtothefuture2": "west",
    "backtothefutureii": "west",
    "backtothefutureiii": "west",
    "ballerina": "west",
    "bandofbrothers": "west",
    "barbie": "west",
    "batmanbegins": "west",
    "batmanvsupermandawnofjustice": "west",
    "beautyandthebeast": "west",
    "benhur": "west",
    "bettercallsaul": "west",
    "beyondevil": "jpkr",
    "bighero6": "west",
    "billions": "west",
    "blackadam": "west",
    "blackmirror": "west",
    "blackpanther": "west",
    "blackpantherwakandaforever": "west",
    "blacksails": "west",
    "blackwidow": "west",
    "bladerunner": "west",
    "bladerunner2049": "west",
    "bleach": "jpkr",
    "bluebeetle": "west",
    "bluelock": "jpkr",
    "bocchitherock": "jpkr",
    "bodyguard": "west",
    "bodyguardsandassassins": "cn",
    "bornfly": "cn",
    "bosch": "west",
    "brave": "west",
    "braveheart": "west",
    "breakingbad": "west",
    "bridgeofspies": "west",
    "bridgerton": "west",
    "bridgeton": "west",
    "bulletinthead": "cn",
    "burning": "west",
    "captainamerica": "west",
    "captainamericabravenewworld": "west",
    "captainamericacivilwar": "west",
    "captainamericathefirstavenger": "west",
    "captainamericathewintersoldier": "west",
    "captainmarvel": "west",
    "cars2": "west",
    "cars3": "west",
    "casino": "west",
    "casinoroyale": "west",
    "castaway": "west",
    "castleinthesky": "jpkr",
    "catchmeifyoucan": "west",
    "chainsawman": "jpkr",
    "chernobyl": "west",
    "chernobyl:thelosttapes": "west",
    "chernobyldisaster": "west",
    "chineseodyssey": "cn",
    "chineseodysseypartone": "cn",
    "chineseodysseyparttwo": "cn",
    "chinesepuzzle": "cn",
    "chungkingexpress": "cn",
    "cityhunter": "cn",
    "cj7": "cn",
    "closeencountersofthethirdkind": "west",
    "coilingdragon": "cn",
    "conair": "west",
    "confucius": "cn",
    "crashlandingonyou": "jpkr",
    "creationofthegods": "cn",
    "creationofthegods2": "cn",
    "creationofthegodsii": "cn",
    "crouchingtigerhiddendragon": "cn",
    "curseofthegoldenflower": "cn",
    "cyberpunkedgerunners": "jpkr",
    "daredevil": "west",
    "daysofwild": "cn",
    "deadpool": "west",
    "deadpool2": "west",
    "deadpoolandwolverine": "west",
    "deathnote": "jpkr",
    "decisiontoleave": "west",
    "demonslayer": "jpkr",
    "despicableme": "west",
    "despicableme2": "west",
    "despicableme3": "west",
    "despicableme4": "west",
    "diehard": "west",
    "diehard2": "west",
    "diehardwithavengeance": "west",
    "doctorstrange": "west",
    "doctorstrangeinthemultiverseofmadness": "west",
    "dontlookup": "west",
    "doupocangqiong": "cn",
    "downtonabbey": "west",
    "dragongate": "cn",
    "dragoninn": "cn",
    "drunkenmaster": "cn",
    "drunkenmaster2": "cn",
    "drunkenmasterii": "cn",
    "dunepart2": "west",
    "dunepartthree": "west",
    "duneparttwo": "west",
    "dunkirk": "west",
    "elemental": "west",
    "encanto": "west",
    "enterthedragon": "cn",
    "eternals": "west",
    "ettheextraterrestrial": "west",
    "everythingeverywhereallatonce": "west",
    "extraction": "west",
    "extraction2": "west",
    "extracurricular": "jpkr",
    "faceoff": "west",
    "falconandthewintersoldier": "west",
    "fallenangels": "cn",
    "fallout": "west",
    "familyguy": "west",
    "fantasticfour": "west",
    "fast11": "west",
    "fastandfurious": "west",
    "fastfive": "west",
    "fastsix": "west",
    "fastx": "west",
    "fightbacktoschool": "cn",
    "fightclub": "west",
    "findingdory": "west",
    "findingnemo": "west",
    "findyourself": "cn",
    "fistoffury": "cn",
    "fistoflegend": "cn",
    "fleabag": "west",
    "fongsauyuk": "cn",
    "forallmankind": "west",
    "forrest": "west",
    "forrestgump": "west",
    "foundation": "west",
    "frieren": "jpkr",
    "frombeijingwithlove": "cn",
    "frozen": "west",
    "frozen2": "west",
    "frozenii": "west",
    "fullmetalalchemist": "jpkr",
    "fullmetaljacket": "west",
    "fullriverred": "cn",
    "furiosa": "west",
    "furious6": "west",
    "furious7": "west",
    "gameofdeath": "cn",
    "gameofthrones": "west",
    "geostorm": "west",
    "gladiator": "west",
    "gladiator2": "west",
    "gladiatorii": "west",
    "goblin": "jpkr",
    "goldenkamuy": "jpkr",
    "goodfellas": "west",
    "grandmasterofdemoniccultivation": "cn",
    "gravesofthefireflies": "jpkr",
    "gravity": "west",
    "greenland": "west",
    "greenlandmigration": "west",
    "greysanatomy": "west",
    "groundhogday": "west",
    "guardiansofthegalaxy": "west",
    "guardiansofthegalaxyvol2": "west",
    "guardiansofthegalaxyvol3": "west",
    "haikyuu": "jpkr",
    "happyend": "jpkr",
    "happytogether": "cn",
    "hardboiled": "cn",
    "hawkeye": "west",
    "heavenofficialsblessing": "cn",
    "hero": "cn",
    "himom": "west",
    "hisdarkmaterials": "west",
    "hobbsandshaw": "west",
    "hometownchachacha": "jpkr",
    "hospitalplaylist": "jpkr",
    "hoteldelluna": "jpkr",
    "hoteltransylvania": "west",
    "hotzone": "west",
    "house": "west",
    "houseofcards": "west",
    "houseofflyingdaggers": "cn",
    "houseofthedragon": "west",
    "howlsmovingcastle": "jpkr",
    "howtotrainyourdragon": "west",
    "howtotrainyourdragon2": "west",
    "howtotrainyourdragon3": "west",
    "iceage": "west",
    "iceage2": "west",
    "iceage3": "west",
    "iceage4": "west",
    "iceage5": "west",
    "inception": "west",
    "incredibles2": "west",
    "independenceday": "west",
    "independencedayresurgence": "west",
    "infernalaffairs": "cn",
    "infernalaffairs2": "cn",
    "infernalaffairsii": "cn",
    "infernalaffairsiii": "cn",
    "insideout": "west",
    "insideout2": "west",
    "interstellar": "west",
    "inthemoodforlove": "cn",
    "invincible": "west",
    "ironman": "west",
    "ironman2": "west",
    "ironman3": "west",
    "itaewonclass": "jpkr",
    "itsokaytonotbeokay": "jpkr",
    "jackryan": "west",
    "johnwick": "west",
    "johnwickchapter2": "west",
    "johnwickchapter3parabellum": "west",
    "johnwickchapter4": "west",
    "joker": "west",
    "jokerfolieadeux": "west",
    "journeytothewest": "cn",
    "journeytothewestaconquestofthedemons": "cn",
    "joyoflife": "cn",
    "jujutsukaisen": "jpkr",
    "jurassicpark": "west",
    "jurassicworld": "west",
    "jurassicworlddominion": "west",
    "jurassicworldrebirth": "west",
    "justiceleague": "west",
    "kikisdeliveryservice": "jpkr",
    "killingeve": "west",
    "kingdom": "west",
    "kingdom2": "west",
    "kingofcomedy": "cn",
    "klaus": "west",
    "kungfuhustle": "cn",
    "kungfupanda": "west",
    "kungfupanda2": "west",
    "kungfupanda3": "west",
    "kungfupanda4": "west",
    "landman": "west",
    "lastmanstanding": "cn",
    "lawrenceofarabia": "west",
    "leontheprofessional": "west",
    "lethalweapon": "west",
    "lethalweapon2": "west",
    "lethalweapon3": "west",
    "lethalweapon4": "west",
    "letthousandsofflowersbloom": "cn",
    "linkclick": "cn",
    "livefreeordiehard": "west",
    "logan": "west",
    "lostinthestars": "cn",
    "lovebetweenfairyanddevil": "cn",
    "madeinabyss": "jpkr",
    "madeinhongkong": "cn",
    "madmax": "west",
    "madmaxfuryroad": "west",
    "manofsteel": "west",
    "marrymydeceasedwife": "cn",
    "memento": "west",
    "migration": "west",
    "minions": "west",
    "minionstheriseofgru": "west",
    "minningtown": "cn",
    "minorityreport": "west",
    "misaeng": "jpkr",
    "missionimpossible": "west",
    "missionimpossibledeadreckoning": "west",
    "missionimpossiblefallout": "west",
    "missionimpossibleghostprotocol": "west",
    "missionimpossibleroguenation": "west",
    "missionimpossiblethefinalreckoning": "west",
    "moana": "west",
    "moana2": "west",
    "mobpsycho100": "jpkr",
    "monstersinc": "west",
    "monstersuniversity": "west",
    "moonfall": "west",
    "moonknight": "west",
    "morbius": "west",
    "mouse": "jpkr",
    "mrsunshine": "jpkr",
    "msmarvel": "west",
    "mulan": "west",
    "munich": "west",
    "mymister": "jpkr",
    "myneighbortotoro": "jpkr",
    "mypeoplemycountry": "west",
    "mypeoplemyhomeland": "west",
    "mypeoplemyparents": "west",
    "naruto": "jpkr",
    "nevergonnagiveyouup": "cn",
    "newdragongateinn": "cn",
    "newhart": "west",
    "newpolicestory": "cn",
    "nezha": "cn",
    "nezha2": "cn",
    "nikita": "west",
    "nirvanainfire": "cn",
    "nocountryforoldmen": "west",
    "noonespeaksofthedead": "cn",
    "normalpeople": "west",
    "nothingbutyou": "cn",
    "notimetodie": "west",
    "noweapons": "cn",
    "oldboy": "west",
    "onandon": "cn",
    "onceuponatimeinchina": "cn",
    "onceuponatimeinchina2": "cn",
    "onceuponatimeinchina3": "cn",
    "onepiece": "jpkr",
    "oneshot": "west",
    "onward": "west",
    "oppenheimer": "west",
    "ordinaryglory": "cn",
    "oshinoko": "jpkr",
    "parasite": "west",
    "peacemaker": "west",
    "peakyblinders": "west",
    "pegasus": "cn",
    "pegasus2": "cn",
    "perfectworld": "cn",
    "platoon": "west",
    "pointbreak": "west",
    "policestory": "cn",
    "policestory2": "cn",
    "ponyo": "jpkr",
    "porcorosso": "jpkr",
    "predator": "west",
    "predator2": "west",
    "predatorbadlands": "west",
    "princessmononoke": "jpkr",
    "prisonbreak": "west",
    "projecta": "cn",
    "projecta2": "cn",
    "projectaii": "cn",
    "prometheus": "west",
    "pulpfiction": "west",
    "pussinboots": "west",
    "pussinbootsthelastwish": "west",
    "ragingbull": "west",
    "ralphbreakstheinternet": "west",
    "ratatouille": "west",
    "reacher": "west",
    "rednotice": "west",
    "returnofthejedi": "west",
    "rickandmorty": "west",
    "robbhood": "cn",
    "robocop": "west",
    "robotdreams": "west",
    "rumbleinthebronx": "cn",
    "runningoutoftime": "cn",
    "sanandreas": "west",
    "savethesun": "cn",
    "savingprivateryan": "west",
    "scarface": "west",
    "schindlerslist": "west",
    "se7en": "west",
    "secretinvasion": "west",
    "seven": "west",
    "severance": "west",
    "sexeducation": "west",
    "shadowandbone": "west",
    "shangchiandthelegendofthetenrings": "west",
    "shaolin": "cn",
    "shaolinsoccer": "cn",
    "shaolinsoccer2": "cn",
    "shazam": "west",
    "shehulk": "west",
    "sherlock": "west",
    "shogun": "west",
    "shrek": "west",
    "shrek2": "west",
    "shrekforeverafter": "west",
    "shrekthethird": "west",
    "silentwitness": "west",
    "siliconvalley": "west",
    "slowhorses": "west",
    "snowwhite": "west",
    "southpark": "west",
    "spartacus": "west",
    "spectre": "west",
    "speed": "west",
    "spiderhead": "west",
    "spiderman": "west",
    "spidermanacrossthespiderverse": "west",
    "spidermanfarfromhome": "west",
    "spidermanhomecoming": "west",
    "spidermannowayhome": "west",
    "spiesindisguise": "west",
    "spiritedaway": "jpkr",
    "spyfamily": "jpkr",
    "squidgame": "jpkr",
    "squidgame2": "jpkr",
    "squidgame3": "jpkr",
    "starshiptroopers": "west",
    "startrek": "west",
    "starwars": "west",
    "starwarsanewhope": "west",
    "strangerthings": "west",
    "succession": "west",
    "successor": "cn",
    "suits": "west",
    "supercop": "cn",
    "superman": "west",
    "supernatural": "west",
    "suzume": "jpkr",
    "swallowedstar": "cn",
    "swordsman": "cn",
    "swordsmanii": "cn",
    "taboo": "west",
    "tangled": "west",
    "taxidriver": "west",
    "tedlasso": "west",
    "tenet": "west",
    "terminator": "west",
    "terminator2judgmentday": "west",
    "terminator3riseofthemachines": "west",
    "terminatordarkfate": "west",
    "terminatorsalvation": "west",
    "terminatorthegenesis": "west",
    "theabyss": "west",
    "theacolyte": "west",
    "theavengers": "west",
    "thebadguys": "west",
    "thebadguys2": "west",
    "thebanquet": "cn",
    "thebatman": "west",
    "thebattleatlakechangjin": "west",
    "thebattleatlakechangjinii": "west",
    "thebear": "west",
    "thebigbangtheory": "west",
    "thebookofbobafett": "west",
    "theboyandtheheron": "west",
    "theboys": "west",
    "thebridewithwhitehair": "cn",
    "thebridgeontheriverkwai": "west",
    "thecreator": "west",
    "thecrown": "west",
    "thecrown2": "west",
    "thedailyshow": "west",
    "thedarkknight": "west",
    "thedarkknightrises": "west",
    "thedayaftertomorrow": "west",
    "thedeparted": "west",
    "thedeviljudge": "jpkr",
    "thedragonfromrusia": "cn",
    "thedropout": "west",
    "theeaglehuntingheroes": "cn",
    "theeighthundred": "west",
    "theempirestrikesback": "west",
    "theexpanse": "west",
    "thefalconandthewintersoldier": "west",
    "thefantasticfourfirststeps": "west",
    "thefateofthefurious": "west",
    "thefifthelement": "west",
    "thefirstslamdunk": "jpkr",
    "theflash": "west",
    "theforceawakens": "west",
    "thefugitive": "west",
    "theglory": "jpkr",
    "thegodfather": "west",
    "thegodfatherpart2": "west",
    "thegodfatherpartii": "west",
    "thegodfatherpartiii": "west",
    "thegodofcookery": "cn",
    "thegooddinosaur": "west",
    "thegooddoctor": "west",
    "thegoodfight": "west",
    "thegoodwife": "west",
    "thegrayman": "west",
    "thegreatesthits": "cn",
    "thehandmaiden": "west",
    "thehobbit": "west",
    "thehotzone": "west",
    "theincrediblehulk": "west",
    "theincredibles": "west",
    "thejoker": "west",
    "thekiller": "cn",
    "theknockout": "cn",
    "thelastdance": "west",
    "thelastjedi": "west",
    "thelastkingdom": "west",
    "thelastofus": "west",
    "thelegend": "cn",
    "thelegendofshenli": "cn",
    "thelionking": "west",
    "thelionking2": "west",
    "thelittlemermaid": "west",
    "thelongestdayinchangan": "cn",
    "thelordoftherings": "west",
    "thelordoftheringstheringsofpower": "west",
    "themandalorian": "west",
    "themariomovie": "west",
    "themartian": "west",
    "themarvels": "west",
    "thematrix": "west",
    "thematrixreloaded": "west",
    "thematrixresurrections": "west",
    "thematrixrevolutions": "west",
    "themission": "cn",
    "themonkeyking": "cn",
    "themorningshow": "west",
    "themother": "west",
    "themyth": "cn",
    "thenewmutants": "west",
    "thenightmanager": "west",
    "thenightmarebeforechristmas": "west",
    "thenutcrackerandthefourrealms": "west",
    "theoldguard": "west",
    "theoldguard2": "west",
    "theoutcast": "cn",
    "thepacific": "west",
    "thepenguin": "west",
    "theprestige": "west",
    "theprofessional": "west",
    "theprosecutor": "cn",
    "theprotector": "cn",
    "thequeensgambit": "west",
    "theread": "west",
    "therewillbeblood": "west",
    "theringsofpower": "west",
    "theriseofskywalker": "west",
    "therock": "west",
    "theshawshankredemption": "west",
    "thesilenceofthelambs": "west",
    "thesimpsons": "west",
    "thesocialnetwork": "west",
    "thesopranos": "west",
    "thesupermariobrosmovie": "west",
    "theterminal": "west",
    "theterminator": "west",
    "thethreebodyproblem": "west",
    "thetreatment": "cn",
    "thetrueman": "cn",
    "thetrumanshow": "west",
    "theuntamed": "cn",
    "thevolunteerstothedsea": "cn",
    "thevolunteerstothesea2": "cn",
    "thewalkingdead": "west",
    "thewanderingearth": "cn",
    "thewanderingearth2": "cn",
    "thewanderingearthii": "cn",
    "thewaroftheworlds": "west",
    "thewheeloftime": "west",
    "thewildrobot": "west",
    "thewindrises": "jpkr",
    "thewire": "west",
    "thewitcher": "west",
    "thewolverine": "west",
    "theworldofthemarried": "west",
    "theyuanfen": "cn",
    "thor2": "west",
    "thorloveandthunder": "west",
    "thorragnarok": "west",
    "thorthedarkworld": "west",
    "thunderbolts": "west",
    "titanic": "west",
    "tokyorevengers": "jpkr",
    "topgun": "west",
    "topgunmaverick": "west",
    "totalrecall": "west",
    "toystory": "west",
    "toystory2": "west",
    "toystory3": "west",
    "toystory4": "west",
    "tremors": "west",
    "triplefrontier": "west",
    "truedetective": "west",
    "truelies": "west",
    "turningred": "west",
    "twentyfivetwentyone": "west",
    "tylerrake": "west",
    "underthelight": "cn",
    "venom": "west",
    "venomlettherebecarnage": "west",
    "venomthelastdance": "west",
    "vicenzo": "jpkr",
    "vikings": "west",
    "vinlandsaga": "jpkr",
    "walle": "west",
    "wandavision": "west",
    "warofthewolds": "west",
    "weatheringwithyou": "jpkr",
    "westworld": "west",
    "whatif": "west",
    "whoknowsmore": "cn",
    "wolverine": "west",
    "wonderwoman": "west",
    "wonderwoman1984": "west",
    "wordofhonor": "cn",
    "wreckitralph": "west",
    "wuxiashijie": "cn",
    "xmenapocalypse": "west",
    "xmendarkphoenix": "west",
    "xmendaysoffuturepast": "west",
    "xmenfirstclass": "west",
    "xmenthelaststand": "west",
    "yellowstone": "west",
    "yolo": "cn",
    "yourlieinapril": "jpkr",
    "yourname": "jpkr",
    "zacksnydersjusticeleague": "west",
    "zootopia": "west",
    "zootopia2": "west",
}

# 归一化一次，避免运行时反复算
_NORM_DICT: dict[str, str] = {}
for _k, _v in BUILTIN_CN.items():
    _NORM_DICT[normalize_en(_k)] = _v
# 同一个 key 可能被上面两种写法重复写入，这里不再覆盖已存在的（先写的优先）

# 短语表：只在整段英文里做「包含」匹配。key 必须够长，短词会误伤片名。
PHRASE_CN: list[tuple[str, str]] = [
    ("dragon gate inn", "新龙门客栈"),
    ("new dragon gate", "新龙门客栈"),
    ("crouching tiger hidden dragon", "卧虎藏龙"),
    ("enter the dragon", "龙争虎斗"),
    ("game of death", "死亡游戏"),
    ("fist of fury", "精武英雄"),
    ("once upon a time in china", "黄飞鸿"),
    ("a chinese odyssey", "大话西游"),
    ("the wandering earth", "流浪地球"),
    ("crouching tiger", "卧虎藏龙"),
    ("kung fu hustle", "功夫"),
    ("shaolin soccer", "少林足球"),
    ("the dark knight", "蝙蝠侠：黑暗骑士"),
    ("star wars", "星球大战"),
    ("lord of the rings", "指环王"),
    ("the hunger games", "饥饿游戏"),
    ("pacific rim", "环太平洋"),
    ("pirates of the caribbean", "加勒比海盗"),
    ("harry potter", "哈利·波特"),
    ("fast and furious", "速度与激情"),
    ("fast & furious", "速度与激情"),
    ("mission impossible", "碟中谍"),
    ("mission: impossible", "碟中谍"),
    ("how to train your dragon", "驯龙高手"),
    ("monsters university", "怪兽大学"),
    ("kung fu panda", "功夫熊猫"),
    ("the good the bad and the ugly", "黄金三镖客"),
    ("the last of us", "最后生还者"),
    ("house of the dragon", "龙之家族"),
    ("game of thrones", "权力的游戏"),
    ("the boys", "黑袍纠察队"),
    ("the bear", "熊家餐馆"),
    ("squid game", "鱿鱼游戏"),
    ("true detective", "真探"),
    ("peaky blinders", "浴血黑帮"),
    ("the three body problem", "三体"),
    ("3 body problem", "三体"),
    ("creation of the gods", "封神"),
    ("the battle at lake changjin", "长津湖"),
    ("my people my country", "我和我的祖国"),
    ("hi mom", "你好，李焕英"),
    ("the world of the married", "夫妻的世界"),
    ("crash landing on you", "爱的迫降"),
    ("all of us are dead", "僵尸校园"),
    ("extraordinary attorney woo", "非常律师禹英禑"),
    ("demon slayer", "鬼灭之刃"),
    ("spy family", "间谍过家家"),
    ("my neighbor totoro", "龙猫"),
    ("howl's moving castle", "哈尔的移动城堡"),
    ("the boy and the heron", "你想活出怎样的人生"),
    ("spider man", "蜘蛛侠"),
    ("iron man", "钢铁侠"),
    ("captain america", "美国队长"),
    ("guardians of the galaxy", "银河护卫队"),
    ("avengers", "复仇者联盟"),
    ("doctor strange", "奇异博士"),
    ("black panther", "黑豹"),
    ("ant man", "蚁人"),
    ("wonder woman", "神奇女侠"),
    ("justice league", "正义联盟"),
    ("john wick", "疾速追杀"),
    ("mad max", "疯狂的麦克斯"),
    ("blade runner", "银翼杀手"),
    ("jurassic world", "侏罗纪世界"),
    ("jurassic park", "侏罗纪公园"),
    ("fast x", "速度与激情10"),
    ("die hard", "虎胆龙威"),
    ("lethal weapon", "致命武器"),
    ("back to the future", "回到未来"),
    ("independence day", "独立日"),
    ("terminator", "终结者"),
    ("toy story", "玩具总动员"),
    ("ice age", "冰河世纪"),
    ("despicable me", "神偷奶爸"),
    ("the lion king", "狮子王"),
    ("the matrix", "黑客帝国"),
    ("star trek", "星际迷航"),
]
# 预归一化（去空格/连字符），匹配时与同样处理过的查询串比较
_NORM_PHRASES: list[tuple[str, str]] = [
    (re.sub(r"[\s\-\._'’]+", "", p.lower()), cn) for p, cn in PHRASE_CN
]


# ---------------------------------------------------------------- 用户自定义
def _dict_path() -> Path:
    return get_data_dir() / "user_dict.json"


def _cache_path() -> Path:
    return get_data_dir() / "media_cache.json"


def _load_user_dict() -> dict[str, str]:
    """用户自定义中英对照：数据目录下 user_dict.json，格式 {"英文": "中文"}。

    放在数据目录而不是代码目录，容器重建不丢，也方便用户自己往里加。
    """
    p = _dict_path()
    if not p.exists():
        return {}
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            return {normalize_en(k): str(v).strip()
                    for k, v in raw.items() if str(v).strip()}
    except Exception:
        pass
    return {}


def _load_disk_cache() -> None:
    global _disk_loaded, _disk_cache
    if _disk_loaded:
        return
    _disk_loaded = True
    p = _cache_path()
    if not p.exists():
        return
    try:
        raw = json.loads(p.read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            _disk_cache = {str(k): v for k, v in raw.items() if isinstance(v, dict)}
    except Exception:
        _disk_cache = {}


def _save_disk_cache() -> None:
    try:
        p = _cache_path()
        p.parent.mkdir(parents=True, exist_ok=True)
        tmp = p.with_suffix(".tmp")
        tmp.write_text(json.dumps(_disk_cache, ensure_ascii=False, indent=0),
                       encoding="utf-8")
        tmp.replace(p)
    except Exception:
        pass  # 缓存写不进去无所谓，下次重查


# ---------------------------------------------------------------- TMDB
def _tmdb_key() -> str:
    """读 TMDB api_key。带进程内缓存——旧实现每条标题都 reload 一次配置文件。"""
    global _tmdb_key_cache
    if _tmdb_key_cache is None:
        try:
            from core.config import AppConfig
            from core.data_dir import resolve_config_path
            _tmdb_key_cache = (AppConfig.load(str(resolve_config_path())).tmdb.api_key or "").strip()
        except Exception:
            _tmdb_key_cache = ""
    return _tmdb_key_cache


_tmdb_key_cache: str | None = None


def _tmdb_search(query: str, kind: str, key: str) -> dict | None:
    """查 TMDB 的 /search/movie 或 /search/tv，返回命中的第一条。"""
    url = (
        f"https://api.themoviedb.org/3/search/{kind}"
        f"?query={urllib.parse.quote(query)}&language=zh-CN&api_key={key}"
    )
    req = urllib.request.Request(url, headers={"User-Agent": "tg-guangya/1.6"})
    with urllib.request.urlopen(req, timeout=6) as resp:
        data = json.loads(resp.read())
    for r in data.get("results") or []:
        title = (r.get("title") or r.get("name") or "").strip()
        if not title:
            continue
        return {
            "cn_name": title,
            "original_language": (r.get("original_language") or "").strip(),
            "year": int(((r.get("release_date") or r.get("first_air_date") or "")[:4] or 0) or 0),
            "source": "tmdb",
        }
    return None


def _tmdb_lookup(query: str, year: int = 0) -> dict | None:
    """先按电影查，再按剧集查（追剧资源以前查不到就是漏了 tv）。"""
    key = _tmdb_key()
    if not key or not query:
        return None
    global _fail_count, _fail_until
    if time.time() < _fail_until:
        return None
    for kind in ("movie", "tv"):
        try:
            hit = _tmdb_search(query, kind, key)
        except Exception:
            _fail_count += 1
            if _fail_count >= _FAIL_LIMIT:
                _fail_until = time.time() + _FAIL_COOLDOWN
                _fail_count = 0
            continue
        # 年份对不上可接受——TMDB 首个结果未必精确，但译名通常是对的
        if hit:
            _fail_count = 0
            return hit
    return None


# ---------------------------------------------------------------- 对外入口
def lookup(title: str, year: int = 0) -> MediaMeta:
    """查一条英文片名的中文译名与原始语言。查不到返回空 MediaMeta。

    :param title: 尽量干净的英文片名（调用方应已剥掉分辨率/编码等噪声）
    :param year:  已知年份，可提升 TMDB 命中率（当前仅用于缓存键）
    """
    if not title or _CJK.search(title):
        return MediaMeta()  # 已经是中文，不需要翻译
    key = f"{normalize_en(title)}|{year or 0}"
    if not key.strip("|"):
        return MediaMeta()

    with _lock:
        hit = _mem_cache.get(key)
        if hit is not None:
            return MediaMeta(**hit)
        _load_disk_cache()
        hit = _disk_cache.get(key)
        if hit is not None:
            _mem_cache[key] = hit
            return MediaMeta(**hit)

        out: dict = {}
        norm = normalize_en(title)

        # 1. 用户自定义字典（用户自己加的，优先级最高）
        ud = _load_user_dict()
        if norm in ud:
            out = {"cn_name": ud[norm], "original_language": "",
                   "year": 0, "region": BUILTIN_REGION.get(norm, ""),
                   "source": "user_dict"}

        # 2. 内置字典精确匹配（带 the 前缀的片名再试一次去掉 the 的形式）
        if not out:
            for cand in (norm, _THE.sub("", norm)):
                if cand and cand in _NORM_DICT:
                    out = {"cn_name": _NORM_DICT[cand], "original_language": "",
                           "year": 0, "region": BUILTIN_REGION.get(cand, ""),
                           "source": "dict"}
                    break

        # 3. 内置短语包含匹配
        if not out:
            for phrase, cn in _NORM_PHRASES:
                if len(phrase) >= 5 and phrase in norm:
                    out = {"cn_name": cn, "original_language": "",
                           "year": 0, "region": BUILTIN_REGION.get(phrase, ""),
                           "source": "dict"}
                    break

        # 4. TMDB（唯一能给出 original_language 的来源）
        if not out or not out.get("region") or not out.get("original_language"):
            tm = _tmdb_lookup(title, year)
            if tm:
                tm["region"] = language_to_region(tm.get("original_language", ""))
                # 本地字典已有译名时，只借用 TMDB 的地区与年份
                if out.get("cn_name"):
                    out["original_language"] = tm.get("original_language", "")
                    out["region"] = out.get("region") or tm.get("region", "")
                    if not out.get("year"):
                        out["year"] = tm.get("year", 0)
                    out["source"] += "+tmdb"
                else:
                    out = tm

        if not out:
            out = {"cn_name": "", "original_language": "", "year": 0,
                   "region": "", "source": ""}

        _mem_cache[key] = out
        _disk_cache[key] = out
        # 每个新查询都落盘代价太高，攒够 20 条或每 10 条写一次
        if len(_disk_cache) % 10 == 0:
            _save_disk_cache()
        return MediaMeta(**out)


def translate(title: str, year: int = 0) -> str:
    """只要译名。查不到返回空串（调用方应保留英文原名）。"""
    return lookup(title, year).cn_name


def language_to_region(lang: str) -> str:
    """TMDB 的 original_language → 本项目地区码。

    这是地区判定里最权威的一路：TMDB 直接告诉你这片子原创语言是什么，
    比靠标题里的「国语/英语」标签猜要准得多。
    """
    lang = (lang or "").lower()
    if lang in ("zh", "cn", "yue", "cmn", "wuu", "nan"):
        return "cn"
    if lang in ("ja", "ko"):
        return "jpkr"
    if lang in ("en", "fr", "de", "es", "it", "ru", "pt", "nl", "sv", "no", "da", "fi", "pl"):
        return "west"
    if lang in ("th", "vi", "id", "ms", "hi", "ta", "te", "tr", "fa", "ar"):
        return "other"
    return ""


def flush() -> None:
    """把内存缓存写回磁盘（进程退出前调用）。"""
    with _lock:
        _save_disk_cache()


def stats() -> dict:
    with _lock:
        _load_disk_cache()
        return {
            "builtin_entries": len(_NORM_DICT),
            "phrases": len(_NORM_PHRASES),
            "cached": len(_disk_cache),
            "tmdb_enabled": bool(_tmdb_key()),
        }
